"use client";

// Копирайт лендинга (issues 36-40) на трёх языках. Переключается тем же
// PrefsProvider, что и приложение, поэтому LanguageSwitcher работает и здесь.
import { usePrefs } from "@/components/providers";

const ru = {
  nav: { map: "Карта", crops: "Культуры", features: "Возможности", how: "Как это работает", faq: "Вопросы", signin: "Войти", dashboard: "Дашборд" },
  hero: {
    eyebrow: "Теплицы и поля на одной карте",
    title: "Выращивайте умнее — все теплицы и поля с одного взгляда",
    sub: "Наведите или кликните любой участок, чтобы увидеть, что растёт сейчас и что будет посажено. Планирование, созревание и прибыль в одном месте.",
    ctaPrimary: "Начать бесплатно",
    ctaSecondary: "Смотреть карту",
    note: "Без установки. Работает в браузере.",
  },
  map: {
    eyebrow: "Карта хозяйства",
    title: "Все теплицы и поля на одной карте",
    sub: "Наведите или кликните участок, чтобы увидеть, что там растёт или что будет посажено.",
    planMode: "Режим планирования",
    planHint: "Кликните свободный участок, чтобы назначить культуру.",
    choose: "Выберите культуру для посадки",
    all: "Все",
    type: { greenhouse: "Теплица", field: "Поле" },
    status: { planted: "Посажено", growing: "Растёт", ready: "К сбору", empty: "Свободно" },
    panel: { crop: "Культура", planned: "Запланировано", plantedOn: "Посадка", harvestOn: "Сбор", area: "Площадь", note: "Заметка", free: "Участок свободен", assign: "Назначить культуру" },
    units: { m2: "м²", ha: "га" },
    names: { gh1: "Теплица 1", gh2: "Теплица 2", gh3: "Теплица 3", gh4: "Теплица 4", f1: "Северное поле", f2: "Южное поле", f3: "Восточное поле", f4: "Западное поле", f5: "Приречное поле" },
    notes: {
      gh1: "Основная теплица, капельный полив.",
      gh2: "Молодая посадка, набирает рост.",
      gh3: "Первый урожай сезона, готов к сбору.",
      gh4: "Свободна после ротации грунта.",
      f1: "Открытое поле, бахчевые культуры.",
      f2: "Ранний посев, укрытие уже снято.",
      f3: "Готово к уборке на этой неделе.",
      f4: "Под пар, ждёт новой посадки.",
      f5: "Полоса у реки, лёгкий полив.",
    },
  },
  stats: {
    eyebrow: "Хозяйство в цифрах",
    title: "Обзор всего хозяйства",
    totalArea: "Общая площадь",
    activeGh: "Активных теплиц",
    growing: "Культур растёт",
    nextHarvest: "Ближайший сбор",
    none: "—",
  },
  cropsStrip: {
    eyebrow: "Культуры",
    title: "Что растёт в хозяйстве",
    sub: "Нажмите культуру, чтобы подсветить её участки на карте.",
    plots: ["участок", "участка", "участков"],
  },
  features: {
    eyebrow: "Возможности",
    title: "Всё для управления теплицей",
    sub: "От планировки грядок до расчёта прибыли.",
    items: [
      { title: "Визуальная сетка грядок", text: "Разметьте теплицу на клетки 1 м и назначьте культуру на любой участок мышью." },
      { title: "Прогноз даты сбора", text: "Модель суточного роста считает готовность культуры по микроклимату и виду." },
      { title: "Умные уведомления", text: "Замедление из за холода, идеальные условия и готовность к сбыту." },
      { title: "Учёт прибыли", text: "Урожайность, выручка, расходы и чистая прибыль по каждой грядке." },
      { title: "Три языка", text: "Интерфейс на русском, қазақша и английском." },
      { title: "Данные в облаке", text: "Доступ с любого устройства, ничего устанавливать не нужно." },
    ],
  },
  how: {
    eyebrow: "Как это работает",
    title: "Три шага до прогноза",
    sub: "От пустой теплицы до плана поставок.",
    steps: [
      { title: "Разметьте теплицу", text: "Создайте теплицу и выделите грядки под культуры на сетке." },
      { title: "Вносите замеры", text: "Температура и влажность за сутки, вручную или с датчиков." },
      { title: "Получайте прогноз", text: "Даты сбора, статусы культур и прибыль обновляются автоматически." },
    ],
  },
  preview: {
    eyebrow: "Обзор",
    title: "Весь урожай на одном экране",
    sub: "Прогресс каждой культуры, готовность и ожидаемая выручка.",
    area: "Площадь", crops: "Культуры", ready: "Готовность", revenue: "Выручка",
    ripening: "Созревание урожая", live: "live", daysLeft: "дн", ready2: "готово",
  },
  faq: {
    eyebrow: "Вопросы",
    title: "Частые вопросы",
    items: [
      { q: "Нужны ли датчики?", a: "Нет. Замеры температуры и влажности можно вносить вручную, а датчики подключить позже." },
      { q: "Как считается дата сбора?", a: "По индексу суточного роста: он учитывает культуру, температуру, влажность и тип выращивания." },
      { q: "Какие культуры поддерживаются?", a: "Более десяти: томаты, огурцы, перец, клубника, зелень и другие. Справочник расширяется." },
      { q: "Сколько это стоит?", a: "MVP доступен бесплатно. Всё, что нужно для планирования и учёта, уже включено." },
      { q: "На каких языках интерфейс?", a: "Русский, қазақша и English. Язык переключается в один клик." },
    ],
  },
  cta: { title: "Готовы вырастить больше?", sub: "Создайте первую теплицу за пару минут.", button: "Начать бесплатно" },
  footer: {
    tagline: "Умное управление теплицами.",
    product: "Продукт", account: "Аккаунт", contactTitle: "Контакты",
    rights: "Все права защищены.", langLabel: "Язык",
  },
};

const kk = {
  nav: { map: "Карта", crops: "Дақылдар", features: "Мүмкіндіктер", how: "Қалай жұмыс істейді", faq: "Сұрақтар", signin: "Кіру", dashboard: "Басқару тақтасы" },
  hero: {
    eyebrow: "Барлық жылыжай мен алаң бір картада",
    title: "Ақылды өсіріңіз — барлық жылыжай мен алаң бір көзқараста",
    sub: "Қазір не өсіп жатқанын және не отырғызылатынын көру үшін кез келген алаңды меңзеңіз немесе басыңыз. Жоспарлау, пісу және пайда бір жерде.",
    ctaPrimary: "Тегін бастау",
    ctaSecondary: "Картаны көру",
    note: "Орнатусыз. Браузерде жұмыс істейді.",
  },
  map: {
    eyebrow: "Шаруашылық картасы",
    title: "Барлық жылыжай мен алаң бір картада",
    sub: "Онда не өсетінін немесе не отырғызылатынын көру үшін алаңды меңзеңіз немесе басыңыз.",
    planMode: "Жоспарлау режимі",
    planHint: "Дақыл тағайындау үшін бос алаңды басыңыз.",
    choose: "Отырғызуға дақыл таңдаңыз",
    all: "Барлығы",
    type: { greenhouse: "Жылыжай", field: "Алаң" },
    status: { planted: "Отырғызылды", growing: "Өсуде", ready: "Жинауға", empty: "Бос" },
    panel: { crop: "Дақыл", planned: "Жоспарланды", plantedOn: "Отырғызу", harvestOn: "Жинау", area: "Аумағы", note: "Ескертпе", free: "Алаң бос", assign: "Дақыл тағайындау" },
    units: { m2: "м²", ha: "га" },
    names: { gh1: "1-жылыжай", gh2: "2-жылыжай", gh3: "3-жылыжай", gh4: "4-жылыжай", f1: "Солтүстік алаң", f2: "Оңтүстік алаң", f3: "Шығыс алаң", f4: "Батыс алаң", f5: "Өзен маңы алаңы" },
    notes: {
      gh1: "Негізгі жылыжай, тамшылатып суару.",
      gh2: "Жас егіс, қарқын алуда.",
      gh3: "Маусымның алғашқы өнімі, жинауға дайын.",
      gh4: "Топырақ ротациясынан кейін бос.",
      f1: "Ашық алаң, бақша дақылдары.",
      f2: "Ерте егіс, жабыны алынған.",
      f3: "Осы аптада жинауға дайын.",
      f4: "Тыңайтуда, егісті күтуде.",
      f5: "Өзен жағасы, жеңіл суару.",
    },
  },
  stats: {
    eyebrow: "Шаруашылық сандармен",
    title: "Бүкіл шаруашылыққа шолу",
    totalArea: "Жалпы аумақ",
    activeGh: "Белсенді жылыжай",
    growing: "Дақыл өсуде",
    nextHarvest: "Жақын жинау",
    none: "—",
  },
  cropsStrip: {
    eyebrow: "Дақылдар",
    title: "Шаруашылықта не өсуде",
    sub: "Картада оның алаңдарын бөлектеу үшін дақылды басыңыз.",
    plots: ["алаң"],
  },
  features: {
    eyebrow: "Мүмкіндіктер",
    title: "Жылыжайды басқаруға қажеттінің бәрі",
    sub: "Егісті жоспарлаудан пайданы есептеуге дейін.",
    items: [
      { title: "Көрнекі егіс торы", text: "Жылыжайды 1 м торға бөліп, кез келген алаңға тінтуірмен дақыл тағайындаңыз." },
      { title: "Жинау күнін болжау", text: "Тәуліктік өсу моделі дақыл мен микроклимат бойынша дайындықты есептейді." },
      { title: "Ақылды хабарламалар", text: "Суықтан баяулау, идеал жағдай және өткізуге дайындық." },
      { title: "Пайда есебі", text: "Әр егіс бойынша өнімділік, түсім, шығын және таза пайда." },
      { title: "Үш тіл", text: "Интерфейс орысша, қазақша және ағылшынша." },
      { title: "Бұлттағы деректер", text: "Кез келген құрылғыдан қолжетімді, ештеңе орнатудың қажеті жоқ." },
    ],
  },
  how: {
    eyebrow: "Қалай жұмыс істейді",
    title: "Болжамға дейін үш қадам",
    sub: "Бос жылыжайдан жеткізу жоспарына дейін.",
    steps: [
      { title: "Жылыжайды бөліңіз", text: "Жылыжай құрып, торда дақылдарға арналған егістерді белгілеңіз." },
      { title: "Өлшеу енгізіңіз", text: "Тәулік температурасы мен ылғалдылығы, қолмен немесе датчиктерден." },
      { title: "Болжам алыңыз", text: "Жинау күндері, дақыл күйі және пайда автоматты жаңарады." },
    ],
  },
  preview: {
    eyebrow: "Шолу",
    title: "Барлық өнім бір экранда",
    sub: "Әр дақылдың барысы, дайындығы және күтілетін түсім.",
    area: "Аумақ", crops: "Дақылдар", ready: "Дайындық", revenue: "Түсім",
    ripening: "Өнімнің пісуі", live: "live", daysLeft: "күн", ready2: "дайын",
  },
  faq: {
    eyebrow: "Сұрақтар",
    title: "Жиі қойылатын сұрақтар",
    items: [
      { q: "Датчиктер қажет пе?", a: "Жоқ. Температура мен ылғалдылықты қолмен енгізуге болады, датчиктерді кейін қосасыз." },
      { q: "Жинау күні қалай есептеледі?", a: "Тәуліктік өсу индексі бойынша: дақыл, температура, ылғалдылық және өсіру түрі ескеріледі." },
      { q: "Қандай дақылдар қолдау табады?", a: "Ондаған: қызанақ, қияр, бұрыш, құлпынай, көкөніс және басқалары. Анықтамалық кеңеюде." },
      { q: "Бұл қанша тұрады?", a: "MVP тегін қолжетімді. Жоспарлау мен есепке қажеттінің бәрі енгізілген." },
      { q: "Интерфейс қай тілде?", a: "Орысша, қазақша және English. Тіл бір басумен ауысады." },
    ],
  },
  cta: { title: "Көбірек өсіруге дайынсыз ба?", sub: "Алғашқы жылыжайды бірер минутта құрыңыз.", button: "Тегін бастау" },
  footer: {
    tagline: "Жылыжайды ақылды басқару.",
    product: "Өнім", account: "Аккаунт", contactTitle: "Байланыс",
    rights: "Барлық құқық қорғалған.", langLabel: "Тіл",
  },
};

const en = {
  nav: { map: "Map", crops: "Crops", features: "Features", how: "How it works", faq: "FAQ", signin: "Sign in", dashboard: "Dashboard" },
  hero: {
    eyebrow: "Every greenhouse and field on one map",
    title: "Grow smarter — see every greenhouse and field at a glance",
    sub: "Hover or click any parcel to see what is growing now and what will be planted. Planning, ripening and profit in one place.",
    ctaPrimary: "Start for free",
    ctaSecondary: "View the map",
    note: "No install. Runs in the browser.",
  },
  map: {
    eyebrow: "Farm map",
    title: "Every greenhouse and field on one map",
    sub: "Hover or click a parcel to see what grows there, or what will be planted.",
    planMode: "Plan mode",
    planHint: "Click an empty parcel to assign a crop.",
    choose: "Choose a crop to plant",
    all: "All",
    type: { greenhouse: "Greenhouse", field: "Field" },
    status: { planted: "Planted", growing: "Growing", ready: "To harvest", empty: "Empty" },
    panel: { crop: "Crop", planned: "Planned", plantedOn: "Planted", harvestOn: "Harvest", area: "Area", note: "Note", free: "Parcel is empty", assign: "Assign a crop" },
    units: { m2: "m²", ha: "ha" },
    names: { gh1: "Greenhouse 1", gh2: "Greenhouse 2", gh3: "Greenhouse 3", gh4: "Greenhouse 4", f1: "North Field", f2: "South Field", f3: "East Field", f4: "West Field", f5: "Riverside Field" },
    notes: {
      gh1: "Main greenhouse, drip irrigation.",
      gh2: "Young planting, gaining growth.",
      gh3: "First harvest of the season, ready to pick.",
      gh4: "Free after soil rotation.",
      f1: "Open field, melon crops.",
      f2: "Early sowing, cover removed.",
      f3: "Ready to harvest this week.",
      f4: "Fallow, waiting for planting.",
      f5: "Strip by the river, light watering.",
    },
  },
  stats: {
    eyebrow: "The farm in numbers",
    title: "An overview of the whole farm",
    totalArea: "Total area",
    activeGh: "Active greenhouses",
    growing: "Crops growing",
    nextHarvest: "Next harvest",
    none: "—",
  },
  cropsStrip: {
    eyebrow: "Crops",
    title: "What is growing on the farm",
    sub: "Click a crop to highlight its parcels on the map.",
    plots: ["plot", "plots"],
  },
  features: {
    eyebrow: "Features",
    title: "Everything to run a greenhouse",
    sub: "From planning beds to calculating profit.",
    items: [
      { title: "Visual bed grid", text: "Split the greenhouse into 1 m cells and assign a crop to any area with the mouse." },
      { title: "Harvest date forecast", text: "A daily growth model estimates crop readiness from microclimate and type." },
      { title: "Smart alerts", text: "Cold slowdown, ideal conditions and ready for sale." },
      { title: "Profit tracking", text: "Yield, revenue, costs and net profit for every bed." },
      { title: "Three languages", text: "Interface in Russian, Kazakh and English." },
      { title: "Data in the cloud", text: "Access from any device, nothing to install." },
    ],
  },
  how: {
    eyebrow: "How it works",
    title: "Three steps to a forecast",
    sub: "From an empty greenhouse to a delivery plan.",
    steps: [
      { title: "Map the greenhouse", text: "Create a greenhouse and mark beds for crops on the grid." },
      { title: "Enter readings", text: "Daily temperature and humidity, by hand or from sensors." },
      { title: "Get the forecast", text: "Harvest dates, crop status and profit update automatically." },
    ],
  },
  preview: {
    eyebrow: "Overview",
    title: "The whole harvest on one screen",
    sub: "Progress of each crop, readiness and expected revenue.",
    area: "Area", crops: "Crops", ready: "Readiness", revenue: "Revenue",
    ripening: "Harvest ripening", live: "live", daysLeft: "d", ready2: "ready",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Frequently asked questions",
    items: [
      { q: "Do I need sensors?", a: "No. You can enter temperature and humidity by hand and connect sensors later." },
      { q: "How is the harvest date calculated?", a: "By a daily growth index that accounts for crop, temperature, humidity and growing type." },
      { q: "Which crops are supported?", a: "More than ten: tomatoes, cucumbers, pepper, strawberry, greens and others. The reference keeps growing." },
      { q: "How much does it cost?", a: "The MVP is free. Everything you need for planning and accounting is included." },
      { q: "What languages are supported?", a: "Russian, Kazakh and English. Switch the language in one click." },
    ],
  },
  cta: { title: "Ready to grow more?", sub: "Create your first greenhouse in a couple of minutes.", button: "Start for free" },
  footer: {
    tagline: "Smart greenhouse management.",
    product: "Product", account: "Account", contactTitle: "Contact",
    rights: "All rights reserved.", langLabel: "Language",
  },
};

export const LANDING = { ru, kk, en };

export function useLanding() {
  const { lang } = usePrefs();
  return LANDING[lang] || LANDING.ru;
}
